### ISSUE TITLE
KubeDB only listed once

### ISSUE THREAD

**Issue by hermanbanken** [operator-framework/awesome-operators#124]
When selecting a good Redis Cluster operator I found KubeDB elsewhere, but in this table it is not clear that it provides operators for:
- elasticsearch,
- memcached,
- mongodb,
- mysql,
- postgresql,
- redis

Multiple paths to go:
- add tags and host this page as something interactive with some tag-filtering on Github Pages?
- add these db's to comment column
- add kubedb also at "#3 Redis Cluster" etc

**Comment by madorn** [comment]
@hermanbanken done. thanks for the suggestion.
