### ISSUE TITLE
Operators built on the new SDK

### ISSUE THREAD

**Issue by matyix** [operator-framework/awesome-operators#2]
Hi

We have built some operators based on the new SDK - see below: 

* https://github.com/banzaicloud/prometheus-jmx-exporter-operator - seamlessly (and non intrusively) monitor any Java app by injecting a Prometheus JMX agent into the pod  (more details here: https://banzaicloud.com/blog/operator-sdk/)
* https://github.com/banzaicloud/infinispan-operator - create/operate Infinispan clusters
* https://github.com/banzaicloud/wildfly-operator - operate a WildFly cluster
* https://github.com/banzaicloud/pvc-operator - dynamically/programatically trigger PV by creating the accounts, class, etc

Let me know if you'd like to list them as they are all based on the new SDK.

**Comment by warmchang** [comment]
@matyix I guess the second should be [infinispan-operator](https://github.com/banzaicloud/infinispan-operator), not [prometheus-jmx-exporter-operator](https://github.com/banzaicloud/prometheus-jmx-exporter-operator) which is the same as the first. :smiley:

**Comment by spahl** [comment]
Could you add a PR for those?

**Comment by matyix** [comment]
@spahl  Yes, I just sent one #6 
Thanks.
