### ISSUE TITLE
Clean up descriptors 

### ISSUE THREAD

**Issue by josepalafox** [operator-framework/awesome-operators#22]
See issue #18

**Comment by josepalafox** [comment]
submitted 4 PRs #23 #24 #25 #26. Each operator now states what the project does using a line pulled either from Wikipedia or their projects Github account.

**Comment by robszumski** [comment]
Thanks for doing this clean up! All of those PRs have merged.

**Comment by robszumski** [comment]
I realized that Github's new fix merge conflicts UI was confusing to me in it's use of bold, and I think I blew away some of your changes. I will try to fix when I have a second. Sorry about that.
