### ISSUE TITLE
Project maintenance status?

### ISSUE THREAD

**Issue by adrianmo** [operator-framework/awesome-operators#47]
It's been two months since the last commit (i.e. 98c354125059608f27221b421c27a3b39c9e49f0) and Pull requests that want to include new operators are piling up. 

Is the project still maintained?

**Comment by madorn** [comment]
@adrianmo our apologies for the delay. all the latest PRs have been merged.

**Comment by thatInfrastructureGuy** [comment]
Hi @madorn are looking for project maintainers for this repo?
