### ISSUE TITLE
Question: Is this list exclusively for Operators, or resources in general? 

### ISSUE THREAD

**Issue by aditya-konarde** [operator-framework/awesome-operators#55]
Hello, we've been internally collecting a list of resources (Talks, presentations, docs) to learn about operators. I was wondering if, like other awesome-* lists, we could add a 'learning resources' section here for people looking for curated videos etc. 

Not sure if that fits in the scope of this list, but would love to see a place where we find all of this :)

CC @surajnarwade

**Comment by madorn** [comment]
@aditya-konarde this is a great idea. We will definitely consider putting a learning resources list together. In the meantime, here are a few good Operator-related resources:

[Go Operator Getting Started Guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md)
[Ansible Operator Getting Started Guide](
https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md)
[Helm Operator Getting Started Guide](
https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md)
[Interactive Operator Tutorial](
https://learn.openshift.com/operatorframework)
