### ISSUE TITLE
Unmaintained: Kong Operator

### ISSUE THREAD

**Issue by aRobinson-R7** [operator-framework/awesome-operators#69]
Hello!
Thanks for creating this list :D

I was wanting to ask about updating the notes on the Kong Operator - it does what it says, however it has not been updated in 2 years and is not compatible with `kubectl v1.7+` - it still uses the `ThirdPartyResource` API, instead of CRDs and so I have not been able to use it / check if it actually works.

I had planned on updating the Operator, but that would take time + learning Go, so wont happen this weekend ;)

Thanks!

**Comment by madorn** [comment]
@aRobinson-R7 thanks for letting us know!
